### ISSUE TITLE
Last Stable Releases Roadmap

### ISSUE THREAD

**Issue by acao** [prisma-labs/graphql-playground#1186]
The last few initiatives for the next and final release(s) please create issues/PRs and suggest other bugs in the comments as needed.

We may do a few betas first so folks can test it, as we want this last release to be as stable as possible.

## Major dependency upgrades
- [x] graphql upgrade  (`introspectionQuery` -> `getIntrospectionQuery()`)
- [x] react upgrade
- [ ] `codemirror-graphql` (should fix several bugs, i maintain this and it's dependencies!)
- [ ] `codemirror` itself, to the latest 5.x version
- [ ] `redux`, `react-redux`, etc upgrades?

## Tooling Issues
- [x] only node 10 seems to work for installs/builds? get node 13 working?
- [x] restore yarn workspaces?
- [x] dependabot config for all lockfiles
- [x] get netlify working again
- [x] typescript upgrade
- [x] react webpack upgrade
- [ ] electron webpack upgrade?
- [ ] react babel upgrade?

## Bugfixes
- [ ] Schema polling feches new schema, does not update the UI #965
- [x] user facing security fixes for electron
- [x] user facing security fixes for react
- [ ] development security fixes?
- [x] Allow scroll in result panel #1023
- [x] allow results to fill the entire pane horizontally #1142
- [x] Update express mw to latest graphql-playground-html #984
- [ ] #1097?
- [ ] #1098?
- [ ] #1141

**Comment by acao** [comment]
@beeman check it out! is this helpful?

**Comment by beeman** [comment]
@acao great list! Here are 2 that I think should come along with the stable:
 
https://github.com/prisma-labs/graphql-playground/pull/1097/files
https://github.com/prisma-labs/graphql-playground/pull/1098/files

**Comment by acao** [comment]
I think we have an RC coming today :D

**Comment by beeman** [comment]
@acao can you add this one too?

https://github.com/prisma-labs/graphql-playground/pull/1104

**Comment by beeman** [comment]
Another candidate: https://github.com/prisma-labs/graphql-playground/pull/1058/files

**Comment by olivierlemasle** [comment]
I think these bug fixes are really mandatory for a "stable" release, because both bugs throw errors by simply clicking on the UI:

- Schema tab not working: #1243, #1248 and #1252 (duplicate issues)
- "Copy CURL" not working: #1219 (I opened a PR to fix this bug)

Thank you.

**Comment by BridgeAR** [comment]
Any updates? It has been a while and it would be great to get a new version out.

**Comment by acao** [comment]
cut a release!

sorry very busy, and maintaining this repo is one of many volunteer efforts

freezing now
